project:
  type: website

website:
  title: "FAIR Universe"
  site-url: https://fair-universe.github.io/
  favicon: images/LBL_Vert_547_rgb.jpg  
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/), with theme from [vetiver](https://github.com/rstudio/vetiver.rstudio.com)"
    left: "&copy; CC-By FAIR Universe"
 
  navbar:
    logo: images/LBL_Vert_547_rgb.jpg
    href: https://openscapes.org
    right:
    # - text: "Home"
    #   href: index.html
    - text: "About"
      href: about.qmd
    - text: "Team"
      href: team.qmd
    - text: "Events"
      href: events.qmd
    - icon: github
      href: https://github.com/FAIR-Universe

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left




# old _site.yml content below for comparison while converting to Quarto
#
# name: "."
# title: "NASA-Openscapes"
# description: |
#   NASA-Openscapes
# favicon: images/openscapes_hex.png  
# output_dir: "docs"
# navbar:
#   logo: images/openscapes_hex.png
#   href: https://openscapes.org
#   right:
#     - text: "Home"
#       href: index.html
#     - text: "About"
#       href: about.html
#     - text: "Mentors"
#       href: mentors.html
#     - text: "Champions"
#       href: champions.html 
#     - text: "Tutorials"
#       href: tutorials.html 
#     - text: "Events"
#       href: events.html
#     - icon: fab fa-twitter
#       href: https://twitter.com/openscapes
#     - icon: fab fa-github
#       href: https://github.com/nasa-openscapes
# output: distill::distill_article
# theme: theme.css
