name: Auto PR and Merge for cosmology leaderboard branches

on:
  push:
    branches:
      - 'cosmology-leaderboard-update-*'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr-merge:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request to master
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          echo "[*] Creating PR from $BRANCH → master"
          gh pr create --base master --head "$BRANCH" --title "Auto: Merge leaderboard update ($BRANCH)" \
            --body "This PR was automatically created from branch \`$BRANCH\`." || echo "[!] PR already exists"

      - name: Merge PR if exists
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          PR_NUMBER=$(gh pr list --head "$BRANCH" --base master --json number --jq '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            echo "[*] Merging PR #$PR_NUMBER"
            gh pr merge "$PR_NUMBER" --squash --admin
          else
            echo "[-] No PR found for $BRANCH"
          fi
        
      # - name: Delete branch after merge
      #   if: success()
      #   run: |
      #     BRANCH="${GITHUB_REF_NAME}"
      #     echo "[*] Deleting branch $BRANCH"
      #     gh api -X DELETE "repos/${GITHUB_REPOSITORY}/git/refs/heads/${BRANCH}" \
      #       && echo "[+] Deleted branch $BRANCH" \
      #       || echo "[-] Failed to delete branch $BRANCH"
