name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the main repository (if needed)
    - name: FAIR-Universe.github.io 
      uses: actions/checkout@v2

    # Step 2: Checkout the other repository (containing the Sphinx source files)
    - name: Checkout Sphinx Source from Another Repository
      uses: actions/checkout@v2
      with:
        repository: FAIR-Universe/HEP-Challenge # The Sphinx source repository
        token: ${{ secrets.GITHUB_TOKEN }}  # Access token stored as a secret
        path: HEP-Challenge/docs/  # Checkout to a folder

    # Step 3: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 4: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure your Sphinx dependencies are in requirements.txt

    # Step 5: Build the documentation using make html
    - name: Build Sphinx Documentation
      run: make html  # Run the Makefile to build the HTML

